" let g:indentLine_char = ''
" let g:indentLine_first_char = ''
" let g:indentLine_char = '⎸'
" let g:indentLine_first_char = '⎸'
let g:indentLine_char = '▏'
let g:indentLine_first_char = '▏'
let g:indentLine_showFirstIndentLevel = 1
let g:indentLine_setColors = 1
autocmd Filetype json let g:indentLine_enabled = 0 " https://github.com/Yggdroot/indentLine/issues/172
