# Color scheme
include tokyonight_night.conf

# Font
font_family      MesloLGS Nerd Font Mono
font_size        19.0

# Tab bar
tab_bar_style    hidden

# Window decorations / padding
hide_window_decorations     titlebar-only
window_padding_width        0

# Misc
resize_in_steps   yes

